[package]
name = "engine"
version = "0.1.0"
authors = ["Matt Garnett <matt.garnett@me.com>"]
edition = "2018"

[dependencies]
bonsai = { vesion = "0.2.0", default-features = false, features = ["u128"] }
ewasm = "0.2.3"
interface = { path = "../common/interface" }
oof = "0.0.2"

